# Generated by Django 5.1 on 2025-12-20 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
    ]
